version: 2
sources:
  - name: gz_raw
    schema: gz_raw_data
    tables:
      - name: product
        identifier: raw_gz_product
        description: products of Greenweez
        columns:
          - name: products_id
            description: the id of products
            tests:
              - unique
              - not_null
          - name: purchase_price
            description: the price of the product purchase
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have on row per product_id found in each orders_id
        columns:
          - name: date_date
            description: date of purchase
          - name: orders_id
            description: the id of orders
            tests:
              - unique
              - not_null
          - name: product_id
            description: the id of products
            tests:
              - unique
              - not_null
          - name: revenue
            description: revenue generated
          - name: quantity
            description: quantity of products
      - name: ship
        identifier: raw_gz_ship
        description: Infos about expeditions
        columns:
          - name: orders_id
            description: Unique identifier for the order
            tests:
              - unique
              - not_null
          - name: final_shipping_fee
            description: C'est quoi déjà?
          - name: log_cost
            description: Logistic cost related to the shipment
          - name: ship_cost
            description: Total cost of the shipment
