version: 2
sources:
  - name: gz_raw
    schema: dbt_quentin
    tables:
      - name: product
        identifier: stg_gz_raw_product
        description: Products of Greenweez
        columns:
          - name: products_id
            description: The ID of products
            tests:
              - unique
              - not_null
          - name: purchase_price
            description: The price of the product purchase
      - name: sales
        identifier: sgt_gz_raw_sales
        description: Sales of Greenweez / one row per product_id found in each orders_id
        columns:
          - name: orders_id
            description: The ID of orders
          - name: pdt_id
            description: The ID of products
          - name: revenue
            description: Revenue generated
          - name: quantity
            description: Quantity of products
        tests:
           - unique:
              column_name: "(orders_id || '-' || pdt_id)"
      - name: ship
        identifier: sgt_gz_raw_ship
        description: Infos about expeditions
        columns:
          - name: orders_id
            description: Unique identifier for the order
            tests:
              - unique
              - not_null
          - name: final_shipping_fee
            description: Final shipping fee (renamed to avoid hyphen issues)
          - name: log_cost
            description: Logistic cost related to the shipment
          - name: ship_cost
            description: Total cost of the shipment