version: 2
sources:
  - name: gz_raw
    schema: gz_raw_data
    tables:
      - name: product
        identifier: raw_gz_product
        description: Products of Greenweez
        columns:
          - name: products_id
            description: The ID of products
            tests:
              - unique
              - not_null
          - name: purchase_price
            description: The price of the product purchase
      - name: sales
        identifier: raw_gz_sales
        description: Sales of Greenweez / one row per product_id found in each orders_id
        columns:
          - name: orders_id
            description: The ID of orders
          - name: product_id
            description: The ID of products
          - name: revenue
            description: Revenue generated
          - name: quantity
            description: Quantity of products
        tests:
          - unique:
            column_name: "CONCAT(CAST(orders_id AS STRING), '-', CAST(product_id AS STRING))"
      - name: ship
        identifier: raw_gz_ship
        description: Infos about expeditions
        columns:
          - name: orders_id
            description: Unique identifier for the order
            tests:
              - unique
              - not_null
          - name: final_shipping_fee
            description: Final shipping fee (renamed to avoid hyphen issues)
          - name: log_cost
            description: Logistic cost related to the shipment
          - name: ship_cost
            description: Total cost of the shipment